name: Ayurveda
description: An ayurvedic information app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_html: ^3.0.0-beta.2
  cached_network_image: ^3.3.0
  flutter_native_splash: ^2.3.5
  launcher_name: ^1.0.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  simple_animations: ^5.0.2
  page_transition: ^2.1.0


launcher_name:
  default: "Aayurveda"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"


flutter_native_splash:
  color: "#FCA608"
  image: assets/images/logo.png
  android_12:
    color: "#FCA608"
    image: assets/images/logo.png
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800

